### PR TITLE
Version 1.0 BETA

### PR DESCRIPTION
**Pull request by Victorb101**
All files associated with Version 1.0 BETA included.  Ready for review and release.

### CODE REVIEW

**Comment by Victorb101** [comment]
@aaronbeekay Please review and pull

**Comment by aaronbeekay** [comment]
Couple of things:

* You have unresolved ERC errors
* You have parts in TI.lbr that haven't been merged into BuckeyeCurrent - you need to submit a PR and merge them before this can be merged

Looks good to my quick review otherwise. Schematic is clean and readable, I appreciate it

**Comment by aaronbeekay** [comment]
* You don't seem to use the IOUT1 signal coming out of your DAC -- I think you probably have a connection error here. ERC will catch these kinds of mistakes.

**Comment by aaronbeekay** [comment]
@Victorb101 Merged. I fixed some ERC errors - please double check these before mfg to make sure that  all ERC errors are OK

**Pull request merged**
